config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/b', to: 'rooms#index', as: 'rooms'
  get '/b/:room_name', to: 'rooms#show', as: 'room'
  post '/b/:room_name', to: 'topics#create'
  get '/b/:room_name/:topic_id', to: 'topics#show', as: 'topic'
  post '/b/:room_name/:topic_id', to: 'replies#create'
  get '/vgv', to: 'static#vgv', as: 'vgv'

  get '/js/preview/:topic_id/:reply_fakeid', to: 'replies#hover', as: 'js_preview'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @topics = Topic.order(bumped_at: :desc).page(params[:p]).includes(:room)
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_topic.html.slim
tr
  td = link_to topic.room.name, room_path(topic.room), class: 'textlink'

  td = link_to topic.subject, topic_path(topic.room, topic)

  td.is-hidden-mobile
    = link_to topic.bumped_at.strftime('%d.%m.%Y %H:%M'),
              topic_path(topic.room, topic, p: topic.last_page, anchor: 'l'),
              class: 'textlink has-text-grey'
  td
    = link_to topic.replies.size,
              topic_path(topic.room, topic, p: topic.last_page, anchor: 'l'),
              class: 'textlink'

app/views/home/index.html.slim
span data-notification-room='home'

table.table.is-fullwidth.is-hoverable
  thead
    tr
      th Kamer
      th Onderwerp
      th.is-hidden-mobile Activiteit
      th: abbr title='Aantal Berichten' #B
  tbody#topics
    - if @topics.length.zero?
      tr: td colspan='4': em (Nog) geen berichten hier!
    - else
      = render partial: 'topic', collection: @topics, cached: true
  tfoot
    tr: td colspan='4' id='paginate'
      = paginate @topics